### ISSUE TITLE
CLI exits with status 1 in npm commands

### ISSUE THREAD

**Issue by herkulano** [renke/import-sort#29]
package.json
`"fix:sort": "import-sort -o ./"`

command
`npm run fix:sort`

debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'fix:sort' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'prefix:sort', 'fix:sort', 'postfix:sort' ]
5 info lifecycle radar-dashboard@0.0.1~prefix:sort: radar-dashboard@0.0.1
6 info lifecycle radar-dashboard@0.0.1~fix:sort: radar-dashboard@0.0.1
7 verbose lifecycle radar-dashboard@0.0.1~fix:sort: unsafe-perm in lifecycle true
8 verbose lifecycle radar-dashboard@0.0.1~fix:sort: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Herc/Documents/RADAR/RADAR-Dashboard/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Herc/Library/Android/sdk/platform-tools:/Users/Herc/Library/Android/sdk/platform-tools
9 verbose lifecycle radar-dashboard@0.0.1~fix:sort: CWD: /Users/Herc/Documents/RADAR/RADAR-Dashboard
10 silly lifecycle radar-dashboard@0.0.1~fix:sort: Args: [ '-c', 'import-sort -o ./' ]
11 silly lifecycle radar-dashboard@0.0.1~fix:sort: Returned: code: 1  signal: null
12 info lifecycle radar-dashboard@0.0.1~fix:sort: Failed to exec fix:sort script
13 verbose stack Error: radar-dashboard@0.0.1 fix:sort: `import-sort -o ./`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid radar-dashboard@0.0.1
15 verbose cwd /Users/Herc/Documents/RADAR/RADAR-Dashboard
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/8.2.1/bin/node" "/usr/local/bin/npm" "run" "fix:sort"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error radar-dashboard@0.0.1 fix:sort: `import-sort -o ./`
22 error Exit status 1
23 error Failed at the radar-dashboard@0.0.1 fix:sort script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Note:
Running `npx import-sort -o ./` exits without errors.

**Comment by briced** [comment]
The exit code is the number of modified files, (https://github.com/renke/import-sort/blob/master/packages/import-sort-cli/src/index.ts)

Problem is, in Unix system, status code 0 is "Everything is ok", every other status is "There's an error"

https://github.com/renke/import-sort/pull/33 should to fix this, but it's a big breaking change, and I don't know if this will be merged.

**Comment by herkulano** [comment]
@briced for `--diff` and `--status` it makes senses to exit with `1` as it means they have found errors.

It's only when you're doing `--write` that it shouldn't exit with `1` because the files have been successfully changed, so they should be correct and there are no errors in them. The write command should only exit with `1` if there's an error writing the files.

**Comment by briced** [comment]
@herkulano 
`--status`, as I understand it, returns the status code, without doing the rewriting (kind of `dry-run`), so it's coherent to make it return 0.
For `--diff` the work is done, so it's normal to return a status code "everything is ok".

If it fails, it will call `bail()` and return -1

**Comment by Frikki** [comment]
Here's how to suppress the status code when different than `0`:

```json
"fix:sort": "import-sort -o './' || true"
```
